### ISSUE TITLE
Tool.Net

### ISSUE THREAD

**Issue by ni-xue** [jasonhua95/awesome-dotnet-core#1]
可以帮我加一个框架吗？
本人也是一个为.net 做贡献的一员。
我提供了，名为：Tool.Net 的框架。
对很多中小型公司有着很大的帮助。
仓库地址：https://github.com/ni-xue/UniversalFrame（里面是一份示例模板）
nuget地址： https://www.nuget.org/packages/Tool.Net

**Comment by jasonhua95** [comment]
一起加油

**Comment by ni-xue** [comment]
共同努力吧！

愿生态圈繁荣。
